version: '3.4'

services:
  k_api202001:
    image: ${DOCKER_REGISTRY-}kapi202001
    environment:
      MYSQLSERVICE_HOST: db
      MYSQLSERVICE_PORT: 3306
      MYSQLDATABASE: YourChoresDb
      MYSQLUSER: DbKh02
      MYSQLPASSWORD: dbuserpassword
    build:
      context: .
      dockerfile: K_Api202001/Dockerfile
    volumes:
      -  api:/app/wwwroot
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dbuserpassword
      MYSQL_DATABASE: YourChoresDb
      MYSQL_USER: DbKh02
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

  nginx:
    image: linuxserver/letsencrypt
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=egypt-youth.com
      - SUBDOMAINS=www,api,admin
      - VALIDATION=http
      - STAGING=true  #false #optional
    volumes:
      - ./nginx/config:/config
      - ./nginx/nginx.conf:/config/nginx/site-confs/default
      - ./nginx/ssl.conf:/config/nginx/ssl.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
volumes:
  dbdata:
  api:



