version: '3.4'

services:
  k_api202001:
    image: ${DOCKER_REGISTRY-}kapi202001
    environment:
      MYSQLSERVICE_HOST: db
      MYSQLSERVICE_PORT: 3306
      MYSQLDATABASE: YourChoresDb
      MYSQLUSER: DbKh02
      MYSQLPASSWORD: dbuserpassword
    build:
      context: .
      dockerfile: K_Api202001/Dockerfile
    ports:
      - "443:443"
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dbuserpassword
      MYSQL_DATABASE: YourChoresDb
      MYSQL_USER: DbKh02
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
volumes:
  dbdata:



